## Objective

predict the test score for the given value of study hours and sleeping hours 

## implementation of a single hidden layer FFD NN using numpy array 


#### Type of problem - Regression    

Architecture:

hidden layers - 1

no. of neurons:

    input layer-2

    hidden layer-3

    output layer-1

activation function - sigmoid (input and hidden)

Weight initialisation type - Random init

Bias - No bias taken as there is only one hidden layer and number of inputs are less

Back propogation - gradient descent

epochs - 500

In [32]:
import numpy as np
import random

### Data generation and normalization

In [33]:
# X = (hours studying, hours sleeping), y = score on test
x = np.array(([2, 9], [1, 5], [3, 6], [5, 10]), dtype=float) # input data as float for calculations
y = np.array(([92], [86], [89]), dtype=float) # output data as float for calcualtions

# Normalization
xAll = xAll/np.amax(xAll, axis=0) # scaling input data
y = y/100 # scaling output data (max test score is 100)

# split data
X = np.split(xAll, [3])[0] # training data
xPredicted = np.split(xAll, [3])[1] # testing data

### Under the Neural_Network() class, functions for forward pass and backward pass are defined

In [57]:


class Neural_Network():

#function for forwrd pass and backward pass
  def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)

    
  def __init__(self):
#number of neurons in each layer
    self.inputSize = 2
    self.outputSize = 1
    self.hiddenSize = 3

#weights attached between layers

# (3x2) weight matrix from input to hidden layer
    self.W1 = np.random.randn(self.inputSize, self.hiddenSize)
# (3x1) weight matrix from hidden to output layer    
    self.W2 = np.random.randn(self.hiddenSize, self.outputSize) 

#forward propagation through our network   

#Matrix multiplications using dot product function

  def forward(self, X):
    
    self.z = np.dot(X, self.W1) 
    self.z2 = self.sigmoid(self.z) # activation function for neurons to fire output to hidden layer
    self.z3 = np.dot(self.z2, self.W2) 
    o = self.sigmoid(self.z3) # final activation function for neurons to fire output to output layer
    return o #output

# activation function for neuron firing
  def sigmoid(self, s):
    return 1/(1+np.exp(-s))

#sigmoid prime is function to find derivative, which helps in building GD algorithm in the end for back propagation
  def sigmoidPrime(self, s):
    return s * (1 - s)

# Backward propagation through the network to correct the weights
  def backward(self, X, y, o):
    
    self.o_error = y - o # error in output, differene in actual and predicted
    self.o_delta = self.o_error*self.sigmoidPrime(o) # applying derivative of sigmoid to error

    self.z2_error = self.o_delta.dot(self.W2.T) # z2 error: how much our hidden layer weights contributed to output error
    self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2) # applying derivative of sigmoid to z2 error

#adjusting weights
    self.W1 += X.T.dot(self.z2_delta) 
    self.W2 += self.z2.T.dot(self.o_delta)
    

In [58]:
NN = Neural_Network()
for i in range(501): #500 epochs
  
  NN.train(X, y)

#After 500 epochs, loss and outputs     
print("Loss: \n" + str(np.mean(np.square(y - NN.forward(X))))) # mean sum squared loss    
print("# " + str(i) + "\n")
print("Input (scaled): \n" + str(X))
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" + str(NN.forward(X)))

Loss: 
0.00011420068108275547
# 500

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90943738]
 [0.87437517]
 [0.88506162]]
